### ISSUE TITLE
Which stage is this training used for?

### ISSUE THREAD

**Issue by petergaoshan** [OpenMOSE/RWKV-LM-RLHF#3]
I see your project combines SFT and ORPO. Is this meant to be use for model trained after SFT or before SFT?

**Comment by OpenMOSE** [comment]
For ORPO training, we simultaneously calculate the preference Loss based on Odds Ratio and the SFT Loss, then set the mixing ratio using a hyperparameter (orpo_alpha).

Therefore, it is basically possible to train directly on the model before SFT.
Since this is PEFT training, it's also possible to inherit the Adapter layer after performing SFT PEFT and then conduct Orpo learning on it.

if you want to try. check this
https://github.com/OpenMOSE/RWKV-LM-RLHF/blob/main/v6/example/ORPO/readme.md

**Comment by petergaoshan** [comment]
> For ORPO training, we simultaneously calculate the preference Loss based on Odds Ratio and the SFT Loss, then set the mixing ratio using a hyperparameter (orpo_alpha).
> 
> Therefore, it is basically possible to train directly on the model before SFT. Since this is PEFT training, it's also possible to inherit the Adapter layer after performing SFT PEFT and then conduct Orpo learning on it.
> 
> if you want to try. check this https://github.com/OpenMOSE/RWKV-LM-RLHF/blob/main/v6/example/ORPO/readme.md

Got it. Thanks for your reply.
